// This file is part of Questournament activity for Moodle - http://moodle.org/
//
// Questournament for Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Questournament for Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Interactive vector scoring chart for Quest challenges.
 *
 * @module     mod_quest/score_chart
 * @copyright  2026 onwards EDUVALab, University of Valladolid
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
define([], function() {
    'use strict';

    /**
     * Format a unix timestamp to a concise human-readable date/time string.
     *
     * @param {number} ts Timestamp in seconds.
     * @returns {string}
     */
    function formatDateTime(ts) {
        var d = new Date(ts * 1000);
        return d.toLocaleDateString(undefined, {month: 'short', day: 'numeric'}) + ' ' +
               d.toLocaleTimeString(undefined, {hour: '2-digit', minute: '2-digit'});
    }

    /**
     * Calculate continuous score at an arbitrary timestamp.
     *
     * @param {Object} data
     * @param {number} t Timestamp in seconds.
     * @returns {number} Score at time t.
     */
    function getScoreAtTime(data, t) {
        var xMin = data.datestart;
        var xMax = data.dateend;
        var pMin = typeof data.pointsmin !== 'undefined' ? data.pointsmin : 0;
        var pMax = data.pointsmax;
        var pInit = data.initialpoints;
        var statEnd = data.stationary_end || (xMin + (data.tinitial || 0));

        if (t <= xMin) {
            return pInit;
        }
        if (t >= xMax) {
            if (data.dateanswercorrect && data.dateanswercorrect <= xMax) {
                return pMin;
            }
            return pMax;
        }

        // Deflationary phase.
        if (data.dateanswercorrect && t > data.dateanswercorrect) {
            var correctScore = getScoreAtTime(data, data.dateanswercorrect);
            var denom = xMax - data.dateanswercorrect;
            if (denom <= 0) {
                return pMin;
            }
            var incline = (correctScore - pMin) / denom;
            var val = correctScore - (incline * (t - data.dateanswercorrect));
            return Math.max(pMin, Math.min(pMax, val));
        }

        // Stationary phase.
        if (t <= statEnd) {
            return pInit;
        }

        // Inflationary phase.
        var inflDuration = xMax - statEnd;
        if (inflDuration <= 0) {
            return pMax;
        }
        var dt = t - statEnd;
        var inflVal = (dt * (pMax - pInit) / inflDuration) + pInit;
        return Math.max(pMin, Math.min(pMax, inflVal));
    }

    /**
     * Render interactive SVG chart inside target element.
     *
     * @param {HTMLElement} container
     * @param {Object} data Chart data generated by scoring_calculator::get_chart_data.
     */
    function renderChart(container, data) {
        container.innerHTML = '';

        // 1:1 aspect ratio (square plot) and smaller footprint.
        var containerWidth = container.clientWidth || 300;
        var size = Math.max(200, Math.min(320, containerWidth));
        var width = size;
        var height = size; // Strict 1:1 aspect ratio.
        var padding = {top: 24, right: 14, bottom: 26, left: 36};
        var plotWidth = Math.max(10, width - padding.left - padding.right);
        var plotHeight = Math.max(10, height - padding.top - padding.bottom);

        var xMin = data.datestart;
        var xMax = data.dateend;
        var yMin = 0;
        var yMax = Math.max(data.pointsmax * 1.12, data.initialpoints * 1.15, 10);

        /**
         * Convert X domain value to pixel coordinate.
         *
         * @param {number} val
         * @returns {number}
         */
        function getX(val) {
            if (xMax <= xMin) {
                return padding.left;
            }
            return padding.left + ((val - xMin) / (xMax - xMin)) * plotWidth;
        }

        /**
         * Convert Y domain value to pixel coordinate.
         *
         * @param {number} val
         * @returns {number}
         */
        function getY(val) {
            if (yMax <= yMin) {
                return padding.top + plotHeight;
            }
            return padding.top + plotHeight - ((val - yMin) / (yMax - yMin)) * plotHeight;
        }

        var svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
        svg.setAttribute('width', '100%');
        svg.setAttribute('height', '100%');
        svg.setAttribute('viewBox', '0 0 ' + width + ' ' + height);
        svg.style.aspectRatio = '1 / 1';
        svg.style.display = 'block';
        svg.style.maxWidth = '100%';
        svg.style.overflow = 'hidden';
        svg.style.fontFamily = 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif';

        // Phase X boundaries.
        var statEnd = Math.min(xMax, data.stationary_end || (xMin + (data.tinitial || 0)));
        var statX = getX(statEnd);

        var hasCorrect = data.dateanswercorrect && data.dateanswercorrect > xMin && data.dateanswercorrect < xMax;
        var inflEnd = hasCorrect ? data.dateanswercorrect : xMax;
        var inflX = getX(inflEnd);
        var endX = getX(xMax);

        // 1. Phase Background Bands.
        var phasesGroup = document.createElementNS('http://www.w3.org/2000/svg', 'g');
        phasesGroup.setAttribute('class', 'chart-phases-bg');

        // Stationary band.
        var statRect = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
        statRect.setAttribute('x', padding.left);
        statRect.setAttribute('y', padding.top);
        statRect.setAttribute('width', Math.max(0, statX - padding.left));
        statRect.setAttribute('height', plotHeight);
        statRect.setAttribute('fill', 'rgba(13, 110, 253, 0.06)');
        phasesGroup.appendChild(statRect);

        // Inflationary band.
        var inflRect = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
        inflRect.setAttribute('x', statX);
        inflRect.setAttribute('y', padding.top);
        inflRect.setAttribute('width', Math.max(0, inflX - statX));
        inflRect.setAttribute('height', plotHeight);
        inflRect.setAttribute('fill', 'rgba(245, 158, 11, 0.08)');
        phasesGroup.appendChild(inflRect);

        // Deflationary band.
        if (hasCorrect) {
            var deflRect = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
            deflRect.setAttribute('x', inflX);
            deflRect.setAttribute('y', padding.top);
            deflRect.setAttribute('width', Math.max(0, endX - inflX));
            deflRect.setAttribute('height', plotHeight);
            deflRect.setAttribute('fill', 'rgba(139, 92, 246, 0.08)');
            phasesGroup.appendChild(deflRect);
        }
        svg.appendChild(phasesGroup);

        // Phase Header Labels inside SVG.
        var labelY = padding.top - 8;
        if (statX - padding.left > 45) {
            var statLabel = document.createElementNS('http://www.w3.org/2000/svg', 'text');
            statLabel.setAttribute('x', (padding.left + statX) / 2);
            statLabel.setAttribute('y', labelY);
            statLabel.setAttribute('text-anchor', 'middle');
            statLabel.setAttribute('font-size', '10');
            statLabel.setAttribute('font-weight', '600');
            statLabel.setAttribute('fill', '#0d6efd');
            statLabel.textContent = 'ESTACIONARIA';
            svg.appendChild(statLabel);
        }

        if (inflX - statX > 45) {
            var inflLabel = document.createElementNS('http://www.w3.org/2000/svg', 'text');
            inflLabel.setAttribute('x', (statX + inflX) / 2);
            inflLabel.setAttribute('y', labelY);
            inflLabel.setAttribute('text-anchor', 'middle');
            inflLabel.setAttribute('font-size', '10');
            inflLabel.setAttribute('font-weight', '600');
            inflLabel.setAttribute('fill', '#d97706');
            inflLabel.textContent = 'INFLACIONARIA';
            svg.appendChild(inflLabel);
        }

        if (hasCorrect && (endX - inflX > 45)) {
            var deflLabel = document.createElementNS('http://www.w3.org/2000/svg', 'text');
            deflLabel.setAttribute('x', (inflX + endX) / 2);
            deflLabel.setAttribute('y', labelY);
            deflLabel.setAttribute('text-anchor', 'middle');
            deflLabel.setAttribute('font-size', '10');
            deflLabel.setAttribute('font-weight', '600');
            deflLabel.setAttribute('fill', '#7c3aed');
            deflLabel.textContent = 'DEFLACIONARIA';
            svg.appendChild(deflLabel);
        }

        // 2. Background Grid.
        var gridGroup = document.createElementNS('http://www.w3.org/2000/svg', 'g');
        gridGroup.setAttribute('class', 'chart-grid');
        gridGroup.setAttribute('stroke', '#e9ecef');
        gridGroup.setAttribute('stroke-dasharray', '3,3');

        // Y grid lines (4 lines).
        for (var i = 0; i <= 4; i++) {
            var yVal = yMin + (i / 4) * (yMax - yMin);
            var yPos = getY(yVal);

            var line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
            line.setAttribute('x1', padding.left);
            line.setAttribute('y1', yPos);
            line.setAttribute('x2', padding.left + plotWidth);
            line.setAttribute('y2', yPos);
            gridGroup.appendChild(line);

            var yLabel = document.createElementNS('http://www.w3.org/2000/svg', 'text');
            yLabel.setAttribute('x', padding.left - 6);
            yLabel.setAttribute('y', yPos + 3);
            yLabel.setAttribute('text-anchor', 'end');
            yLabel.setAttribute('font-size', '10');
            yLabel.setAttribute('fill', '#6c757d');
            yLabel.textContent = Math.round(yVal);
            svg.appendChild(yLabel);
        }

        // Phase vertical boundary lines.
        var statDiv = document.createElementNS('http://www.w3.org/2000/svg', 'line');
        statDiv.setAttribute('x1', statX);
        statDiv.setAttribute('y1', padding.top);
        statDiv.setAttribute('x2', statX);
        statDiv.setAttribute('y2', padding.top + plotHeight);
        statDiv.setAttribute('stroke', 'rgba(13, 110, 253, 0.3)');
        statDiv.setAttribute('stroke-dasharray', '2,2');
        gridGroup.appendChild(statDiv);

        if (hasCorrect) {
            var inflDiv = document.createElementNS('http://www.w3.org/2000/svg', 'line');
            inflDiv.setAttribute('x1', inflX);
            inflDiv.setAttribute('y1', padding.top);
            inflDiv.setAttribute('x2', inflX);
            inflDiv.setAttribute('y2', padding.top + plotHeight);
            inflDiv.setAttribute('stroke', 'rgba(139, 92, 246, 0.3)');
            inflDiv.setAttribute('stroke-dasharray', '2,2');
            gridGroup.appendChild(inflDiv);
        }
        svg.appendChild(gridGroup);

        // 3. CURVA POR TRAMOS (Stationary, Inflationary, Deflationary Segments).
        // Tramo 1: Estacionario.
        var statY = getY(data.initialpoints);
        var statPath = document.createElementNS('http://www.w3.org/2000/svg', 'line');
        statPath.setAttribute('x1', padding.left);
        statPath.setAttribute('y1', statY);
        statPath.setAttribute('x2', statX);
        statPath.setAttribute('y2', statY);
        statPath.setAttribute('stroke', '#0d6efd');
        statPath.setAttribute('stroke-width', '3.5');
        statPath.setAttribute('stroke-linecap', 'round');
        svg.appendChild(statPath);

        // Tramo 2: Inflacionario.
        var inflEndY = getY(getScoreAtTime(data, inflEnd));
        var inflPath = document.createElementNS('http://www.w3.org/2000/svg', 'line');
        inflPath.setAttribute('x1', statX);
        inflPath.setAttribute('y1', statY);
        inflPath.setAttribute('x2', inflX);
        inflPath.setAttribute('y2', inflEndY);
        inflPath.setAttribute('stroke', '#f59e0b');
        inflPath.setAttribute('stroke-width', '3.5');
        inflPath.setAttribute('stroke-linecap', 'round');
        svg.appendChild(inflPath);

        // Tramo 3: Deflacionario (actual, if correct answer exists).
        if (hasCorrect) {
            var deflEndY = getY(data.pointsmin || 0);
            var deflPath = document.createElementNS('http://www.w3.org/2000/svg', 'line');
            deflPath.setAttribute('x1', inflX);
            deflPath.setAttribute('y1', inflEndY);
            deflPath.setAttribute('x2', endX);
            deflPath.setAttribute('y2', deflEndY);
            deflPath.setAttribute('stroke', '#8b5cf6');
            deflPath.setAttribute('stroke-width', '3.5');
            deflPath.setAttribute('stroke-linecap', 'round');
            svg.appendChild(deflPath);
        }

        // Hypothetical dotted deflation projection (always shown: from end-of-inflation to dateend).
        // When hasCorrect: shows what WOULD have happened if no answer had been given (full deflation).
        // When !hasCorrect: shows the future projection from current inflation end.
        {
            var projInflEnd = hasCorrect ? data.dateanswercorrect : inflEnd;
            var projInflX = getX(projInflEnd);
            var projInflY = getY(getScoreAtTime(data, projInflEnd));
            var projEndY = getY(data.pointsmin || 0);
            var projPath = document.createElementNS('http://www.w3.org/2000/svg', 'line');
            projPath.setAttribute('x1', projInflX);
            projPath.setAttribute('y1', projInflY);
            projPath.setAttribute('x2', endX);
            projPath.setAttribute('y2', projEndY);
            projPath.setAttribute('stroke', '#8b5cf6');
            projPath.setAttribute('stroke-width', hasCorrect ? '1.5' : '2');
            projPath.setAttribute('stroke-dasharray', '4,3');
            projPath.setAttribute('opacity', hasCorrect ? '0.35' : '0.6');
            svg.appendChild(projPath);
        }

        // Phase Transition Dots.
        var statDot = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
        statDot.setAttribute('cx', statX);
        statDot.setAttribute('cy', statY);
        statDot.setAttribute('r', '4');
        statDot.setAttribute('fill', '#0d6efd');
        statDot.setAttribute('stroke', '#fff');
        statDot.setAttribute('stroke-width', '2');
        svg.appendChild(statDot);

        if (hasCorrect) {
            var correctDot = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
            correctDot.setAttribute('cx', inflX);
            correctDot.setAttribute('cy', inflEndY);
            correctDot.setAttribute('r', '5');
            correctDot.setAttribute('fill', '#f59e0b');
            correctDot.setAttribute('stroke', '#fff');
            correctDot.setAttribute('stroke-width', '2');
            svg.appendChild(correctDot);
        }

        // Worst-case trajectory if multiple answers.
        if (data.worstcasecurve && data.worstcasecurve.length > 1) {
            var worstD = 'M ' + getX(data.worstcasecurve[0].x) + ' ' + getY(data.worstcasecurve[0].y);
            for (var k = 1; k < data.worstcasecurve.length; k++) {
                worstD += ' L ' + getX(data.worstcasecurve[k].x) + ' ' + getY(data.worstcasecurve[k].y);
            }
            var worstPath = document.createElementNS('http://www.w3.org/2000/svg', 'path');
            worstPath.setAttribute('d', worstD);
            worstPath.setAttribute('fill', 'none');
            worstPath.setAttribute('stroke', '#dc3545');
            worstPath.setAttribute('stroke-width', '1.5');
            worstPath.setAttribute('stroke-dasharray', '4,3');
            svg.appendChild(worstPath);
        }

        // Date labels on X axis.
        var startDateLabel = document.createElementNS('http://www.w3.org/2000/svg', 'text');
        startDateLabel.setAttribute('x', padding.left);
        startDateLabel.setAttribute('y', padding.top + plotHeight + 16);
        startDateLabel.setAttribute('font-size', '10');
        startDateLabel.setAttribute('fill', '#6c757d');
        startDateLabel.textContent = formatDateTime(xMin);
        svg.appendChild(startDateLabel);

        var endDateLabel = document.createElementNS('http://www.w3.org/2000/svg', 'text');
        endDateLabel.setAttribute('x', padding.left + plotWidth);
        endDateLabel.setAttribute('y', padding.top + plotHeight + 16);
        endDateLabel.setAttribute('text-anchor', 'end');
        endDateLabel.setAttribute('font-size', '10');
        endDateLabel.setAttribute('fill', '#6c757d');
        endDateLabel.textContent = formatDateTime(xMax);
        svg.appendChild(endDateLabel);

        // "Now" vertical line and current points indicator.
        if (data.timenow >= xMin && data.timenow <= xMax) {
            var nowX = getX(data.timenow);
            var nowScore = getScoreAtTime(data, data.timenow);
            var nowY = getY(nowScore);

            var nowLine = document.createElementNS('http://www.w3.org/2000/svg', 'line');
            nowLine.setAttribute('x1', nowX);
            nowLine.setAttribute('y1', padding.top);
            nowLine.setAttribute('x2', nowX);
            nowLine.setAttribute('y2', padding.top + plotHeight);
            nowLine.setAttribute('stroke', '#198754');
            nowLine.setAttribute('stroke-width', '2');
            nowLine.setAttribute('stroke-dasharray', '4,2');
            svg.appendChild(nowLine);

            var nowDot = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
            nowDot.setAttribute('cx', nowX);
            nowDot.setAttribute('cy', nowY);
            nowDot.setAttribute('r', '6');
            nowDot.setAttribute('fill', '#198754');
            nowDot.setAttribute('stroke', '#fff');
            nowDot.setAttribute('stroke-width', '2');
            svg.appendChild(nowDot);

            var nowLabel = document.createElementNS('http://www.w3.org/2000/svg', 'text');
            var labelPosX = (nowX + 90 > width) ? (nowX - 8) : (nowX + 6);
            var labelAnchor = (nowX + 90 > width) ? 'end' : 'start';
            nowLabel.setAttribute('x', labelPosX);
            nowLabel.setAttribute('y', Math.max(padding.top + 14, nowY - 7));
            nowLabel.setAttribute('text-anchor', labelAnchor);
            nowLabel.setAttribute('font-size', '11');
            nowLabel.setAttribute('font-weight', 'bold');
            nowLabel.setAttribute('fill', '#198754');
            nowLabel.textContent = Math.round(nowScore * 10) / 10 + ' pts';
            svg.appendChild(nowLabel);
        }

        // 4. Interactive Hover Marker (Aligned strictly to cursor position).
        var hoverLine = document.createElementNS('http://www.w3.org/2000/svg', 'line');
        hoverLine.setAttribute('stroke', '#212529');
        hoverLine.setAttribute('stroke-width', '1.5');
        hoverLine.setAttribute('stroke-dasharray', '3,2');
        hoverLine.style.display = 'none';
        svg.appendChild(hoverLine);

        var hoverDot = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
        hoverDot.setAttribute('r', '5.5');
        hoverDot.setAttribute('fill', '#0d6efd');
        hoverDot.setAttribute('stroke', '#fff');
        hoverDot.setAttribute('stroke-width', '2');
        hoverDot.style.display = 'none';
        svg.appendChild(hoverDot);

        var tooltip = document.createElement('div');
        tooltip.style.position = 'absolute';
        tooltip.style.display = 'none';
        tooltip.style.backgroundColor = 'rgba(17, 24, 39, 0.94)';
        tooltip.style.color = '#fff';
        tooltip.style.padding = '5px 9px';
        tooltip.style.borderRadius = '4px';
        tooltip.style.fontSize = '11px';
        tooltip.style.pointerEvents = 'none';
        tooltip.style.zIndex = '1000';
        tooltip.style.boxShadow = '0 3px 10px rgba(0,0,0,0.25)';
        tooltip.style.whiteSpace = 'nowrap';
        container.style.position = 'relative';
        container.appendChild(tooltip);

        svg.addEventListener('mousemove', function(e) {
            var rect = svg.getBoundingClientRect();
            if (!rect.width) {
                return;
            }

            // Convert client screen mouse coordinates to SVG viewBox coordinate space.
            var scaleX = width / rect.width;
            var mouseX = (e.clientX - rect.left) * scaleX;

            if (mouseX < padding.left || mouseX > padding.left + plotWidth) {
                hoverLine.style.display = 'none';
                hoverDot.style.display = 'none';
                tooltip.style.display = 'none';
                return;
            }

            // Calculate precise continuous time & score matching exact cursor position.
            var ratio = (mouseX - padding.left) / plotWidth;
            var timeVal = xMin + ratio * (xMax - xMin);
            var scoreVal = Math.round(getScoreAtTime(data, timeVal) * 10) / 10;

            var ptX = mouseX;
            var ptY = getY(scoreVal);

            // Anchor vertical indicator line directly to cursor position.
            hoverLine.setAttribute('x1', ptX);
            hoverLine.setAttribute('y1', padding.top);
            hoverLine.setAttribute('x2', ptX);
            hoverLine.setAttribute('y2', padding.top + plotHeight);
            hoverLine.style.display = 'block';

            // Anchor dot exactly onto the curve at cursor X position.
            hoverDot.setAttribute('cx', ptX);
            hoverDot.setAttribute('cy', ptY);
            hoverDot.style.display = 'block';

            // Determine active phase for hover position.
            var phaseText = 'Estacionaria';
            var phaseColor = '#0d6efd';
            if (hasCorrect && timeVal > data.dateanswercorrect) {
                phaseText = 'Deflacionaria';
                phaseColor = '#8b5cf6';
            } else if (timeVal > statEnd) {
                phaseText = 'Inflacionaria';
                phaseColor = '#f59e0b';
            }

            tooltip.innerHTML = '<strong style="color: ' + phaseColor + ';">' + scoreVal +
                ' pts</strong> (' + phaseText + ')<br>' + formatDateTime(timeVal);
            tooltip.style.display = 'block';

            var containerWidth = container.clientWidth || width;
            var tooltipLeft = (ptX / width) * containerWidth;
            tooltip.style.left = Math.min(containerWidth - 130, Math.max(10, tooltipLeft - 50)) + 'px';
            tooltip.style.top = Math.max(5, (ptY / height) * container.clientHeight - 48) + 'px';
        });

        svg.addEventListener('mouseleave', function() {
            hoverLine.style.display = 'none';
            hoverDot.style.display = 'none';
            tooltip.style.display = 'none';
        });

        container.appendChild(svg);
    }

    return {
        /**
         * Initialize an interactive score chart on a container element.
         *
         * @param {string|HTMLElement} containerSelector CSS selector or ID.
         * @param {Object} chartData Curve data.
         */
        init: function(containerSelector, chartData) {
            var container = typeof containerSelector === 'string' ?
                document.querySelector(containerSelector) : containerSelector;
            if (!container) {
                return;
            }

            renderChart(container, chartData);

            // Responsive layout observer.
            var resizeTimeout;
            if (typeof ResizeObserver !== 'undefined') {
                var ro = new ResizeObserver(function(entries) {
                    for (var i = 0; i < entries.length; i++) {
                        if (entries[i].contentRect.width > 0) {
                            clearTimeout(resizeTimeout);
                            resizeTimeout = setTimeout(function() {
                                renderChart(container, chartData);
                            }, 100);
                        }
                    }
                });
                ro.observe(container);
            } else {
                window.addEventListener('resize', function() {
                    clearTimeout(resizeTimeout);
                    resizeTimeout = setTimeout(function() {
                        renderChart(container, chartData);
                    }, 100);
                });
            }
        }
    };
});
